{
    "name": "Customisation of fields",
    "summary": "Customisation for Thailand Erp",
    "author": "Planet-odoo",
    "website": "www.planet-odoo.com",
    "category": "Sales",
    "version": "14.0.1.0.0",
    "depends": ['base','sale','hr_expense','purchase','project','mrp','sale_mrp','sale_management',],
    # "depends": ["base", "sale",'hr_expense','purchase','project',],
    "data": [
        "security/ir.model.access.csv",
        "data/product.xml",
        "wizard/confirm_sale_order_view.xml",
        "views/purchase_order_view.xml",
        "views/stock_picking_view.xml",
        # "views/purchase_discount_view.xml",
        # "views/report_purchaseorder.xml",
        "views/sale_order.xml",
        "views/mrp_bom_view.xml",
        "views/res_partner_view.xml",
        "views/job_cost_view.xml",
        "views/product_template_view.xml",
        "views/project_view.xml",
        "views/account_move_view.xml",
        "wizard/so_excel_report_view.xml",

        # "wizard/confirm_sale_order_view.xml",
        "wizard/job_cost_excel_report_view.xml",
        # "wizard/confirm_wh_loc.xml",
        "reports/header_footer_template.xml",
        "reports/inherit_so_report.xml",
        "reports/so_report_without_partno_template.xml",
        "reports/boq_qweb_report_template.xml",
        "reports/boq_report_without_partno_template.xml",
        "reports/boq_child_with_part_price_template.xml",
        "reports/boq_child_withoutpart_withoutprice_template.xml",
        "reports/boq_child_withoutpart_withprice_template.xml",
        "reports/boq_child_withpart_withoutprice_template.xml",
        "reports/boq_qweb_report.xml",
        # "reports/purchase_report_template.xml",
        "reports/so_report_without_partno.xml",

    ],
}
